import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Tag from '../../app/models/tag.js'
import { TagType } from '../../app/enums/index.js'

export default class TagSeeder extends BaseSeeder {
  async run() {
    // Skills 🛠️
    await Tag.createMany([
      { name: '📜 JavaScript', type: TagType.SKILL },
      { name: '📘 TypeScript', type: TagType.SKILL },
      { name: '🐍 Python', type: TagType.SKILL },
      { name: '☕ Java', type: TagType.SKILL },
      { name: '♯ C#', type: TagType.SKILL },
      { name: '🐘 PHP', type: TagType.SKILL },
      { name: '🐹 Go', type: TagType.SKILL },
      { name: '🦀 Rust', type: TagType.SKILL },
      { name: '🐦 Swift', type: TagType.SKILL },
      { name: '📱 Kotlin', type: TagType.SKILL },
      { name: '🌐 HTML', type: TagType.SKILL },
      { name: '🎨 CSS', type: TagType.SKILL },
      { name: '🗃️ SQL', type: TagType.SKILL },
      { name: '🗄️ NoSQL', type: TagType.SKILL },
      { name: '🍃 MongoDB', type: TagType.SKILL },
      { name: '🐘 PostgreSQL', type: TagType.SKILL },
      { name: '🐬 MySQL', type: TagType.SKILL },
      { name: '⚡ Redis', type: TagType.SKILL },
      { name: '🐳 Docker', type: TagType.SKILL },
      { name: '☸️ Kubernetes', type: TagType.SKILL },
      { name: '☁️ AWS', type: TagType.SKILL },
      { name: '🟦 Azure', type: TagType.SKILL },
      { name: '🇬 GCP', type: TagType.SKILL },
      { name: '🐙 Git', type: TagType.SKILL },
      { name: '⚙️ DevOps', type: TagType.SKILL },
      { name: '🔄 CI/CD', type: TagType.SKILL },
      { name: '🧪 Testing', type: TagType.SKILL },
      { name: '🏃‍♂️ Agile', type: TagType.SKILL },
      { name: '🏉 Scrum', type: TagType.SKILL },
      { name: '🚦 TDD', type: TagType.SKILL },
      { name: '🤖 Machine Learning', type: TagType.SKILL },
      { name: '📊 Data Science', type: TagType.SKILL },
      { name: '🖌️ UI/UX', type: TagType.SKILL },
      { name: '🎨 Design', type: TagType.SKILL },
      { name: '📈 Análise de Dados', type: TagType.SKILL },
      { name: '🛡️ Cybersecurity', type: TagType.SKILL },
      { name: '⛓️ Blockchain', type: TagType.SKILL },
      { name: '📱 Mobile Development', type: TagType.SKILL },
      { name: '💻 Web Development', type: TagType.SKILL },
      { name: '🎮 Game Development', type: TagType.SKILL },
    ])

    // Frameworks 🏗️
    await Tag.createMany([
      { name: '⚛️ React', type: TagType.FRAMEWORK },
      { name: '🖼️ Vue.js', type: TagType.FRAMEWORK },
      { name: '🅰️ Angular', type: TagType.FRAMEWORK },
      { name: '🟢 Node.js', type: TagType.FRAMEWORK },
      { name: '🚀 Express', type: TagType.FRAMEWORK },
      { name: '🎸 Django', type: TagType.FRAMEWORK },
      { name: '🍶 Flask', type: TagType.FRAMEWORK },
      { name: '🌱 Spring Boot', type: TagType.FRAMEWORK },
      { name: '💎 Laravel', type: TagType.FRAMEWORK },
      { name: '🛤️ Ruby on Rails', type: TagType.FRAMEWORK },
      { name: '🌐 ASP.NET', type: TagType.FRAMEWORK },
      { name: '▶️ Next.js', type: TagType.FRAMEWORK },
      { name: '💚 Nuxt.js', type: TagType.FRAMEWORK },
      { name: '� Svelte', type: TagType.FRAMEWORK },
      { name: '⚛️ React Native', type: TagType.FRAMEWORK },
      { name: '🐦 Flutter', type: TagType.FRAMEWORK },
      { name: '⚡ Ionic', type: TagType.FRAMEWORK },
      { name: '📱 Xamarin', type: TagType.FRAMEWORK },
      { name: '🧠 TensorFlow', type: TagType.FRAMEWORK },
      { name: '🔥 PyTorch', type: TagType.FRAMEWORK },
      { name: '🇰 Keras', type: TagType.FRAMEWORK },
      { name: '🐼 Pandas', type: TagType.FRAMEWORK },
      { name: '🔢 NumPy', type: TagType.FRAMEWORK },
      { name: '🤖 Scikit-learn', type: TagType.FRAMEWORK },
      { name: '👁️ OpenCV', type: TagType.FRAMEWORK },
      { name: '🕹️ Unity', type: TagType.FRAMEWORK },
      { name: '🇺 Unreal Engine', type: TagType.FRAMEWORK },
      { name: '⚛️ Electron', type: TagType.FRAMEWORK },
      { name: '💨 Tailwind CSS', type: TagType.FRAMEWORK },
      { name: '🅱️ Bootstrap', type: TagType.FRAMEWORK },
      { name: 'Ⓜ️ Material-UI', type: TagType.FRAMEWORK },
      { name: '⚡ Chakra UI', type: TagType.FRAMEWORK },
      { name: '🐜 Ant Design', type: TagType.FRAMEWORK },
      { name: '💫 Quasar', type: TagType.FRAMEWORK },
      { name: '🇻 Vuetify', type: TagType.FRAMEWORK },
      { name: '🅰️ AdonisJS', type: TagType.FRAMEWORK },
      { name: '둥지 NestJS', type: TagType.FRAMEWORK },
      { name: '🏎️ Fastify', type: TagType.FRAMEWORK },
      { name: '🍸 Gin', type: TagType.FRAMEWORK },
      { name: '🧵 Fiber', type: TagType.FRAMEWORK },
    ])

    // Languages 🗣️
    await Tag.createMany([
      { name: '🇧🇷 Português', type: TagType.LANGUAGE },
      { name: '🇺🇸 Inglês', type: TagType.LANGUAGE },
      { name: '🇪🇸 Espanhol', type: TagType.LANGUAGE },
      { name: '🇫🇷 Francês', type: TagType.LANGUAGE },
      { name: '🇩🇪 Alemão', type: TagType.LANGUAGE },
      { name: '🇮🇹 Italiano', type: TagType.LANGUAGE },
      { name: '🇯🇵 Japonês', type: TagType.LANGUAGE },
      { name: '🇨🇳 Chinês', type: TagType.LANGUAGE },
      { name: '🇰🇷 Coreano', type: TagType.LANGUAGE },
      { name: '🇷🇺 Russo', type: TagType.LANGUAGE },
      { name: '🇸🇦 Árabe', type: TagType.LANGUAGE },
      { name: '🇮🇳 Hindi', type: TagType.LANGUAGE },
    ])

    // Benefits 🎁
    await Tag.createMany([
      { name: '🏥 Plano de Saúde', type: TagType.BENEFIT },
      { name: '🦷 Plano Odontológico', type: TagType.BENEFIT },
      { name: '🍔 Vale Refeição', type: TagType.BENEFIT },
      { name: '🛒 Vale Alimentação', type: TagType.BENEFIT },
      { name: '🚌 Vale Transporte', type: TagType.BENEFIT },
      { name: '🏠 Trabalho Híbrido', type: TagType.BENEFIT },
      { name: '⏰ Flexibilidade de Horário', type: TagType.BENEFIT },
      { name: '💪 Gympass', type: TagType.BENEFIT },
      { name: '💰 Participação nos Lucros', type: TagType.BENEFIT },
      { name: '👶 Auxílio Creche', type: TagType.BENEFIT },
      { name: '🎓 Auxílio Educação', type: TagType.BENEFIT },
      { name: '❤️ Seguro de Vida', type: TagType.BENEFIT },
      { name: '🏦 Previdência Privada', type: TagType.BENEFIT },
      { name: '🎂 Day Off Aniversário', type: TagType.BENEFIT },
      { name: '🤰 Licença Maternidade Estendida', type: TagType.BENEFIT },
      { name: '👨‍🍼 Licença Paternidade Estendida', type: TagType.BENEFIT },
      { name: '📶 Auxílio Internet', type: TagType.BENEFIT },
      { name: '💻 Auxílio Equipamento', type: TagType.BENEFIT },
      { name: '🅿️ Estacionamento Gratuito', type: TagType.BENEFIT },
      { name: '☕🥐 Café da Manhã', type: TagType.BENEFIT },
      { name: '🍽️ Almoço Gratuito', type: TagType.BENEFIT },
      { name: '🛋️ Espaço de Descanso', type: TagType.BENEFIT },
      { name: '📚 Biblioteca', type: TagType.BENEFIT },
      { name: '👨‍🏫 Treinamentos', type: TagType.BENEFIT },
      { name: '📜 Certificações', type: TagType.BENEFIT },
      { name: '🎤 Conferências', type: TagType.BENEFIT },
      { name: '🤝 Mentoria', type: TagType.BENEFIT },
      { name: '📈 Plano de Carreira', type: TagType.BENEFIT },
      { name: '📈💰 Stock Options', type: TagType.BENEFIT },
      { name: '🏆 Bônus por Performance', type: TagType.BENEFIT },
      { name: '✈️ Viagem a Trabalho', type: TagType.BENEFIT },
      { name: '🌍 Trabalho Internacional', type: TagType.BENEFIT },
      { name: '🐾 PetFriendly', type: TagType.BENEFIT },
      { name: '🌈 Diversidade e Inclusão', type: TagType.BENEFIT },
    ])

    // Contract Types 📄
    await Tag.createMany([
      { name: '📝 CLT', type: TagType.CONTRACT },
      { name: '💼 PJ', type: TagType.CONTRACT },
      { name: '👨‍💻 Freelancer', type: TagType.CONTRACT },
      { name: '🧑‍🎓 Estágio', type: TagType.CONTRACT },
      { name: '🌱 Trainee', type: TagType.CONTRACT },
      { name: '⏳ Temporário', type: TagType.CONTRACT },
      { name: '🌗 Meio Período', type: TagType.CONTRACT },
      { name: '🌕 Integral', type: TagType.CONTRACT },
      { name: '🤝 Cooperativo', type: TagType.CONTRACT },
      { name: '➡️ Terceirizado', type: TagType.CONTRACT },
      { name: '🗣️ Consultoria', type: TagType.CONTRACT },
      { name: '🏗️ Projeto', type: TagType.CONTRACT },
    ])

    // Locations 📍
    await Tag.createMany([
      { name: '🏙️ São Paulo', type: TagType.LOCATION },
      { name: '🏖️ Rio de Janeiro', type: TagType.LOCATION },
      { name: '🧀 Belo Horizonte', type: TagType.LOCATION },
      { name: '🧉 Porto Alegre', type: TagType.LOCATION },
      { name: '🏛️ Brasília', type: TagType.LOCATION },
      { name: '🌲 Curitiba', type: TagType.LOCATION },
      { name: '🦀 Recife', type: TagType.LOCATION },
      { name: '🥁 Salvador', type: TagType.LOCATION },
      { name: '☀️ Fortaleza', type: TagType.LOCATION },
      { name: '🏝️ Florianópolis', type: TagType.LOCATION },
      { name: '💡 Campinas', type: TagType.LOCATION },
      { name: '🤠 Goiânia', type: TagType.LOCATION },
      { name: '🌳 Manaus', type: TagType.LOCATION },
      { name: '🥭 Belém', type: TagType.LOCATION },
      { name: '☀️ Natal', type: TagType.LOCATION },
      { name: '☀️ João Pessoa', type: TagType.LOCATION },
      { name: '🌊 Maceió', type: TagType.LOCATION },
      { name: '🦀 Aracaju', type: TagType.LOCATION },
      { name: '🏝️ Vitória', type: TagType.LOCATION },
      { name: '🐂 Campo Grande', type: TagType.LOCATION },
      { name: '☀️ Cuiabá', type: TagType.LOCATION },
      { name: '☀️ Teresina', type: TagType.LOCATION },
      { name: '🟦 São Luís', type: TagType.LOCATION },
      { name: '🌴 Palmas', type: TagType.LOCATION },
      { name: '👀 Boa Vista', type: TagType.LOCATION },
      { name: '🌐 Macapá', type: TagType.LOCATION },
      { name: '⚪ Rio Branco', type: TagType.LOCATION },
      { name: '⚓ Porto Velho', type: TagType.LOCATION },
      { name: '🏠 Remoto', type: TagType.LOCATION },
      { name: '🏢🏠 Híbrido', type: TagType.LOCATION },
      { name: '🏢 Presencial', type: TagType.LOCATION },
      { name: '🌍 Internacional', type: TagType.LOCATION },
    ])

    console.log('✅ Tags criadas com sucesso!')
  }
}
